### ISSUE TITLE
Indexer - TheLeachZone - Unable to Add - Redirected to Login

### ISSUE THREAD

**Issue by DevYukine** [Prowlarr/Prowlarr#136]
**Describe the bug**
Trying to add TheLeachZone will not work when verifying/testing before its added, it fails with `Unable to connect to indexer. We are being redirected to the PTP login page. Most likely your session expired or was killed. Try testing the indexer in the settings.`

This might be related that the login page has a small captcha which will redirect you to the login page if you fail/ignore it.

**To Reproduce**
1. Go to `Add Indexer`
2. Add TheLeachZone
3. Enter credentials
4. Test the indexer
4. See error --> `Unable to connect to indexer. We are being redirected to the PTP login page. Most likely your session expired or was killed. Try testing the indexer in the settings.`

**Expected behavior**
That it would verify correctly

**Screenshots**

Not really needed

**Platform Information (please complete the following information):**
 - OS:  Docker
 - Docker:  Yes
 - .NET Version (System -> Status):  .NET 5.0.1
 - Browser and Version (Only needed for UI issues): 
 - Prowlarr Version:  0.1.0.361
 - Prowlarr Branch:  develop

Turn on Trace logs under Settings -> General and wait for the bug to occur again.
**Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**

https://gist.github.com/DevYukine/84d3c540abe5b3126e64bf4972499170

[AB#48](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/48)

**Comment by Qstick** [comment]
Let's try build 413

**Comment by DevYukine** [comment]
Just tested with 0.1.0.413, still same error

**Comment by Qstick** [comment]
Paste is expired. I assume this is still issue on 447?

**Comment by DevYukine** [comment]
Just tested on `0.1.0.450`, still same error. Also replaced the Ghostbin with a Gist so it doesn't expire

**Comment by bakerboy448** [comment]
I'm assuming still an issue on the 6XX builds?

**Comment by DevYukine** [comment]
Same issue still on `0.1.0.686`

**Comment by bakerboy448** [comment]
Any chance this has been resolved somewhere among the cardigann commits and YML definitions?

**Comment by DevYukine** [comment]
Nope exactly same issue on `0.1.6.1173`

**Comment by Qstick** [comment]
Need an invite

**Comment by DevYukine** [comment]
Invite was sent 👍

**Comment by 1ColdAssHonkey** [comment]
Any update on this issue?  
Still not able to add the site to prowlarr.

**Comment by Nolij** [comment]
> Any update on this issue? Still not able to add the site to prowlarr.

Same here.

**Comment by Nolij** [comment]
> Comments such as "same here" or "me too" are not helpful nor productive.
> 
> If the issue is open with no comments nor pull request or commit linking it then there is no update.

Actually, it means you have another data point and tester.

**Comment by Blurple3333** [comment]
Just wondering if any progress has been made on this fix ..may not be a real world issue but i have had several people asking about it .i am the owner of this site and if we need to change or add something for your service to work just let me know ok .seems a shame for all of us to lose out on users over something that might be fixed with a simple e-mail or DM

**Comment by garfield69** [comment]
Jackett's cardigann auto solves the simplecapture, and I use Jackett's theLeachZone indexer without issues.
I'm confident that the prowlerr team can use our source to retrofit their version of the cardigann processor if required.
https://github.com/Jackett/Jackett/blob/cdb9491593a7347670a8408f0dba8fcabddcbe6a/src/Jackett.Common/Indexers/CardigannIndexer.cs#L656-L666

**Comment by bakerboy448** [comment]
Simple captcha does exist in the Prowlarr code.  Of course possible that's not working.

This could also be the annoying redirect type / cookie issue as well.

At least the two likely causes.

**Comment by Qstick** [comment]
Can we have a go on Build 0.4.3.1881
